debug: true
map_frame: map
odom_frame: odom
base_frame: base_footprint

robot_radius: 0.275

# sample
dock:
  dock_speed: 0.1
  dock_distance: 0.40
  pose_x: -0.058
  pose_y: -0.770
  pose_z: 0.035
  orientation_x: 0.0
  orientation_y: 0.0
  orientation_z: -0.583
  orientation_w: 0.812
