# please visit http://wiki.ros.org/amcl

min_particles: 100                      # (int, default: 100)
max_particles: 5000                     # (int, default: 5000)
kld_err: 0.005                          # (double, default: 0.01)
kld_z: 0.23                             # (double, default: 0.99)
update_min_d: 0.1                       # (double, default: 0.2 meters)
update_min_a: 0.1                       # (double, default: π/6.0 radians)
resample_interval: 2                    # (int, default: 2)
transform_tolerance: 0.1                # (double, default: 0.1 seconds)
recovery_alpha_slow: 0.0                # (disabled)
recovery_alpha_fast: 0.0                # (disabled)
initial_pose_x: 0.0                     # (double, default: 0.0 meters)
initial_pose_y: 0.0                     # (double, default: 0.0 meters)
initial_pose_a: 0.0                     # (double, default: 0.0 radians)
# initial_cov_xx: 0.25                    # (double, default: 0.5*0.5 meters)
# initial_cov_yy: 0.25                    # (double, default: 0.5*0.5 meters)
# initial_cov_aa: 0.0                     # (double, default: (π/12)*(π/12) radian)
gui_publish_rate: 50.0                  # (double, default: -1.0 Hz)
save_pose_rate: 2                       # (double, default: 0.5 Hz)
use_map_topic: false                    # (bool, default: false)
first_map_only: false                   # (bool, default: false)

# laser
laser_min_range: -1.0                   # (double default: -1.0)
laser_max_range: 12.0                   # (double, default: -1.0)
laser_max_beams: 30                     # (int, default: 30)
laser_z_hit: 0.95                       # (double, default: 0.95)
laser_z_short: 0.1                      # (double, default: 0.1)
laser_z_max: 0.05                       # (double, default: 0.05)
laser_z_rand: 0.05                      # (double, default: 0.05)
laser_sigma_hit: 0.2                    # (double, default: 0.2 meters)
laser_lambda_short: 0.1                 # (double, default: 0.1)
laser_likelihood_max_dist: 2.0          # (double, default: 2.0 meters)
laser_model_type: likelihood_field      # (string, default: likelihood_field)

# odom
odom_model_type: diff                   # (string, default: diff)
odom_alpha1: 0.2                        # (double, default: 0.2)
odom_alpha2: 0.2                        # (double, default: 0.2)
odom_alpha3: 0.2                        # (double, default: 0.2)
odom_alpha4: 0.2                        # (double, default: 0.2)
odom_frame_id: odom                     # (string, default: odom)
base_frame_id: base_footprint           # (string, default: base_link)
global_frame_id: map                    # (string, default: "map")
tf_broadcast: true                      # (bool, default: true)