# footprint: [[-0.105, -0.105], [-0.105, 0.105], [0.041, 0.105], [0.041, -0.105]]
# only base
# robot_radius: 0.275 
# have arm
robot_radius: 0.282
footprint_padding: 0.02

#layer definitions
static_layer:
    map_topic: map
    subscribe_to_updates: true

obstacle_layer:
    observation_sources: laser
    laser: {topic: scan, sensor_frame: laser_link, data_type: LaserScan, clearing: true, marking: true, inf_is_valid: true}

# obstacle_range: 4.0
# raytrace_range: 5.0

inflation_layer:
    inflation_radius: 1.0
    cost_scaling_factor: 5 