inverted_laser: false               # default "false"
throttle_scans: 1                   # default 1

base_frame: "base_footprint"        # default "base_link"
map_frame: "map"                    # default "map"
odom_frame: "odom"                  # default "odom"

map_update_interval: 5.0            # default 5.0
maxUrange: 10.0                     # default 80.0
sigma: 0.05                         # default 0.05
kernelSize: 1                       # default 1
lstep: 0.05                         # default 0.05
astep: 0.05                         # default 0.05
iterations: 5                       # default 5
lsigma: 0.075                       # default 0.075
ogain: 3.0                          # default 3.0
lskip: 0                            # default 0
minimumScore: 0.0                   # default 0.0

srr: 0.1                            # default 0.1
srt: 0.2                            # default 0.2
str: 0.1                            # default 0.1
stt: 0.2                            # default 0.2

linearUpdate: 1.0                   # default 1.0
angularUpdate: 0.5                  # default 0.5
temporalUpdate: -1.0                # default -1.0
resampleThreshold: 0.5              # default 0.5
particles: 30                       # default 30

xmin: -100.0                        # default -100.0
ymin: -100.0                        # default -100.0
xmax: 100.0                         # default 100.0
ymax: 100.0                         # default 100.0

delta: 0.05                         # default 0.05

llsamplerange: 0.01                 # default 0.01
llsamplestep: 0.01                  # default 0.01
lasamplerange: 0.005                # default 0.005
lasamplestep: 0.005                 # default 0.005

transform_publish_period: 0.02      # default 0.05
occ_thresh: 0.25                    # default 0.25

maxRange: 20                       # no default value
