local_costmap:
  global_frame: odom
  robot_base_frame: base_footprint

  update_frequency: 8.0
  publish_frequency: 8.0
  transform_tolerance: 0.55  

  static_map: false  
  rolling_window: true
  width: 4
  height: 4
  resolution: 0.05
  
  plugins:
  - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
  - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
