debug: true
map_frame: map
odom_frame: odom
base_frame: base_footprint

robot_radius: 0.275

# dock_test map
dock:
  dock_speed: 0.1
  dock_distance: 0.6
  pose_x: -0.223
  pose_y: 0.250
  pose_z: 0.00
  orientation_x: 0.000
  orientation_y: 0.002
  orientation_z: -0.073
  orientation_w: 0.997
