debug: true
map_frame: map
odom_frame: odom
base_frame: base_footprint

robot_radius: 0.275

# sample
dock:
  dock_speed: 0.1
  dock_distance: 0.65
  pose_x: 0.216
  pose_y: -1.144
  pose_z: 0.00
  orientation_x: 0.000
  orientation_y: -0.001
  orientation_z: -0.225
  orientation_w: 0.974
